### ISSUE TITLE
AuthLayout component missing!!

### ISSUE THREAD

**Issue by Shubbu03** [altence/lightence-ant-design-react-template#276]
when setting up the project locally it is giving the following issue - >
<img width="1440" alt="Screenshot 2023-08-31 at 12 06 47 PM" src="https://github.com/altence/lightence-ant-design-react-template/assets/76101994/58a35473-63df-46a6-9c2d-a7abb7e2c971">

**Comment by Rozhkow** [comment]
Thank you for reaching out to us. We appreciate your interest in the Lightence platform.
As far as I can see, the issue is that you haven't built the application. To run it correctly, please follow these steps:
yarn install
yarn build
yarn start
If you have any remaining questions, we'll be happy to address them.
